### ISSUE TITLE
Adjust Custom View

### ISSUE THREAD

**Issue by anni-phantom** [phantomcyber/reversinglabs-ticloud#14]
Hi the custom view for the widget does not seem to work when the input file is not found. I added a random png file to the vault and then ran the file reputation action. The widget was "stuck" in loading. 
![screen shot 2018-01-12 at 1 10 38 pm](https://user-images.githubusercontent.com/32144874/34895319-1433ed18-f79a-11e7-8f19-ffbb119a9c74.png)

**Comment by pzhou-splunk** [comment]
Hello!

This repo has been migrated to our new GitHub org. Please find a copy of this issue at https://github.com/splunk-soar-connectors/reversinglabs-ticloud/issues/1
